export const linkedInCertificationsUrl = "https://www.linkedin.com/in/remi-rossello/details/certifications/";

export const certificationItems = [
  {
    section: "Engineering",
    title: "Engineering Degree",
    issuer: "École des Mines de Nancy",
    date: "Issued 2024",
    diplomaImage: "/assets/images/engineering-diploma.png",
  },
  {
    section: "Computer Science",
    title: "Introduction to Scala Course",
    issuer: "DataCamp",
    date: "Issued Feb 2026",
    logoUrl: "https://www.google.com/s2/favicons?sz=128&domain=datacamp.com",
    credentialUrl:
      "https://www.datacamp.com/completed/statement-of-accomplishment/course/1056fcbaccaf5269242357074ab325a89de9f97c",
    diplomaImage: "/assets/images/scala-certif.png",
  },
  {
    section: "Computer Science",
    title: "Learn Git: Introduction Course",
    issuer: "Codecademy",
    date: "Issued Dec 2025",
    logoUrl: "https://www.google.com/s2/favicons?sz=128&domain=codecademy.com",
    credentialUrl: "https://www.codecademy.com/profiles/RosselloRemi/certificates/53f1ee480e524cd7b329b5854507c089",
    diplomaImage: "/assets/images/git-certif.png",
  },
  {
    section: "Computer Science",
    title: "Certification - Ada Programming Language",
    issuer: "Udemy",
    date: "Issued Dec 2025",
    credentialId: "UC-ea7a7b27-1c86-44b8-a4c3-32f55de55dea719e",
    logoUrl: "https://www.google.com/s2/favicons?sz=128&domain=udemy.com",
    credentialUrl: "https://www.udemy.com/certificate/UC-ea7a7b27-1c86-44b8-a4c3-32f55dea719e/",
    diplomaImage: "/assets/images/ada-certif.png",
  },
  {
    section: "Computer Science",
    title: "Learn TypeScript Course",
    issuer: "Codecademy",
    date: "Issued Dec 2025",
    logoUrl: "https://www.google.com/s2/favicons?sz=128&domain=codecademy.com",
    credentialUrl: "https://www.codecademy.com/profiles/RosselloRemi/certificates/56fb1e71303e37b643bb1905f31c8a09",
    diplomaImage: "/assets/images/typescript-certif.png",
  },
  {
    section: "Computer Science",
    title: "Intro to Cloud Computing Course",
    issuer: "Codecademy",
    date: "Issued Nov 2025",
    logoUrl: "https://www.google.com/s2/favicons?sz=128&domain=codecademy.com",
    credentialUrl: "https://www.codecademy.com/profiles/RosselloRemi/certificates/1353857e7ad5c1d0d578073e0d5e31e4",
    diplomaImage: "/assets/images/cloud-certif.png",
  },
  {
    section: "Computer Science",
    title: "Full-Stack Development",
    issuer: "Mimo",
    date: "Issued Nov 2025",
    credentialId: "09ec10ed-260c-4d8c-874c-8264c4d1d0d8",
    logoUrl: "https://www.google.com/s2/favicons?sz=128&domain=mimo.org",
    credentialUrl: "https://www.virtualbadge.io/certificate-validator?credential=09ec10ed-260c-4d8c-874c-8264c4d1d0d8",
    diplomaImage: "/assets/images/full-stack-certif.png",
  },
  {
    section: "Humanities",
    title: "IELTS - C1 level",
    issuer: "British Council",
    date: "Issued Jul 2022 · Expires Jul 2024",
    credentialId: "A3-FR585-S-7501954",
    logoUrl: "https://www.google.com/s2/favicons?sz=128&domain=britishcouncil.org",
    credentialUrl: linkedInCertificationsUrl,
  },
  {
    section: "Humanities",
    title: "Greek and Roman Mythology MOOC",
    issuer: "University of Pennsylvania",
    date: "Issued Jun 2022",
    logoUrl: "https://www.google.com/s2/favicons?sz=128&domain=upenn.edu",
    credentialUrl: linkedInCertificationsUrl,
  },
  {
    section: "Humanities",
    title: "Human Behavioral Biology (2010 Lecture Series)",
    issuer: "Stanford University (Robert Sapolsky)",
    date: "2010",
    logoUrl: "https://www.google.com/s2/favicons?sz=128&domain=stanford.edu",
    credentialUrl: "https://www.youtube.com/playlist?list=PL848F2368C90DDC3D",
    linkLabel: "Youtube link",
  },
  {
    section: "Humanities",
    title: "MOOC Gestion de Projet, Attestation session 18 Parcours Classique",
    issuer: "MOOC Gestion de Projet",
    date: "Issued Dec 2021 · Expires Dec 2024",
    credentialId: "GdP18a-MiAyndUyC",
    logoUrl: "https://www.google.com/s2/favicons?sz=128&domain=gestiondeprojet.pm",
    credentialUrl: linkedInCertificationsUrl,
    diplomaImage: "/assets/images/gestion-projet-certif.png",
  },
  {
    section: "Computer Science",
    title: "Elements of AI (collaboration with Reaktor)",
    issuer: "University of Helsinki",
    date: "Issued Mar 2019",
    logoUrl: "https://www.google.com/s2/favicons?sz=128&domain=helsinki.fi",
    credentialUrl: "https://certificates.mooc.fi/validate/9authjljnwq",
    diplomaImage: "/assets/images/AI-certif.png",
  },
];
